version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: walletpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
