# fly.toml app configuration file generated for hakuna-wallet on 2025-10-17T18:43:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hakuna-wallet'
primary_region = 'dfw'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  APP_ENV = 'prod'
  TT_EVENT_ID = 'ev_6873576'
  TT_BASE_URL = 'https://api.tickettailor.com/v1'
  DATABASE_URL= 'postgres://wallet:walletpass@db:5432/walletdb?sslmode=disable'
  APPLE_ROOT_CERT_PATH = '/tmp/certs/apple_root.cer'
  APPLE_P12_PATH = '/tmp/certs/signing.p12'
  APPLE_PASS_TYPE_IDENTIFIER = 'pass.hakuna'
  APPLE_TEAM_IDENTIFIER = 'T2L94M239S'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[files]]
  guest_path = '/tmp/certs/signing.p12'
  secret_name = 'APPLE_P12_BASE64'

[[files]]
  guest_path = '/tmp/certs/apple_root.cer'
  secret_name = 'APPLE_ROOT_CERT_BASE64'
